### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#1]
- [x] Typeface: Open sans

- [x] Always capitalize 'F' in LimbForge

- [x] Update iPad to newest version

- [x] Photo on iPad looks cropped incorrectly 

- [x] Can we establish a neater grid system for supporters logos?

- [ ] Make sponsor logos mono-color 

    - [x] Get SVGs for Autodesk Foundation and Colorfabb

- [x] Add centered ECF logo to footer (small)

- [x] decrease header logo size a little bit

- [x] decrease menu type size and move closer together

- [x] move 'terms of use' and 'privacy' in line with final ECF logo (see how GitHub does it on the bottom of this page)

**Comment by kaitlynhova** [comment]
@hobe12  can you send me an .ai file with the newest ipad vector? Also, we can't make the logos mono-color until the svgs are all in. I'm still missing:
- Autodesk Foundation
- ColorFabb

We also need:

- [x] Add 501c3 info to footer (waiting on Grace info)

**Comment by andreasbastian** [comment]
FYI, we need to get in touch with google.org to get their sign off on the
use of their logo on the new website-- will send out additional info after
I excavate it... I'm having coffee with our grant manager there tomorrow,
will mention the new website.

**Comment by hobe12** [comment]
I will take care of the Google sign off.  @kaitlynhova, do you want a vector rendered ipad in AI or just a photo?

**Comment by andreasbastian** [comment]
Great, thanks for handling that.

- [x]  Can I also add replacing the "(tm)" on LimbForge with the ASCII ™?

**Comment by kaitlynhova** [comment]
@hobe12 can you send me a new vector for the ipad/desktop image?

**Comment by hobe12** [comment]
How’s this? Finding a vector one was harder than I thought.


S A M  H O B I S H 
samhobish.com <http://www.samhobish.com/> / 914.450.7465

**Comment by kaitlynhova** [comment]
@hobe12 Can you upload it? I don't think it attached to your comment

**Comment by kaitlynhova** [comment]
Since we are moving to a new platform i'm going to close this issue
