### ISSUE TITLE
Announcement from Grace

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#10]
We need to discuss how to do this: https://docs.google.com/document/d/1-GmqsFm6D2GoSpxZKbic0oZRqTa7gMl-EAM-LwHVNHk/edit

**Comment by kaitlynhova** [comment]
It really depends on how we want to display it. 

1) If it's an alert:

<img width="954" alt="screen shot 2017-02-26 at 11 38 13 am" src="https://cloud.githubusercontent.com/assets/5474124/23342949/23f0826c-fc18-11e6-839b-8b3129d6079a.png">

2) if it's a note:
<img width="958" alt="screen shot 2017-02-26 at 11 40 54 am" src="https://cloud.githubusercontent.com/assets/5474124/23342977/8e8bbad8-fc18-11e6-8d33-d5624602dfc9.png">

<img width="954" alt="screen shot 2017-02-26 at 11 43 43 am" src="https://cloud.githubusercontent.com/assets/5474124/23342991/d951c1fc-fc18-11e6-9fc6-38a55f816182.png">


^^ are any of these going in the right direction? Ignore the precise styles for right now.

**Comment by hobe12** [comment]
Yes- i like the first direction so far. 

S A M  H O B I S H 
samhobish.com <http://www.samhobish.com/> / 914.450.7465

**Comment by kaitlynhova** [comment]
@hobe12  Can you get copy for the announcement  ?
