### ISSUE TITLE
Donate area 

### ISSUE THREAD

**Issue by kaitlynhova** [e-nable/website#12]
We need to have a donate area with more than one button.

We need:

1) Copy 
2) links for the different types of donations
3) A way to put a link to this area in the top Nav

@hobe12 can you make a wire of all the information ^^^

**Comment by kaitlynhova** [comment]
@hobe12 Does this need to be on this website or can this live on your new website platform?

**Comment by hobe12** [comment]
Just leave it the way it is for now please


S A M  H O B I S H 
samhobish.com <http://www.samhobish.com/> / 914.450.7465

**Comment by kaitlynhova** [comment]
Ah ok gotcha, then I'm going to close this git issue
