### ISSUE TITLE
Banner edits

### ISSUE THREAD

**Issue by andreasbastian** [e-nable/website#3]
- [x] Update banner to add problem statement with text emphasized as below, with smaller ECF logo centered and below the problem statement

<img width="634" alt="screenshot 2017-02-17 10 01 27" src="https://cloud.githubusercontent.com/assets/5185511/23077563/f22333bc-f4f9-11e6-840f-a1b586b025d6.png">

**Comment by kaitlynhova** [comment]
@andreasbastian the type weights for Open Sans ended up not being that different -- I updated the bold text to also be blue. [What do you think of this](https://ecf-website.herokuapp.com/)?

**Comment by kaitlynhova** [comment]
Original copy from @hobe12:
```
Millions of people around the world living with limb-loss to not have access to prosthetic care.

ECF builds intuitive 3D tools so international clinicians can quickly provide patients with high-quality and cost-effective prosthetic devices.
```

@andreasbastian what do you think of that copy? ^^

**Comment by andreasbastian** [comment]
@hobe12, I'm not sure the blue text works-- too noisy?  I'd opt for leaving
all the text white and using the abbreviated hero image text:

Millions of people around the world living with limb-loss to not have
access to prosthetic care.

ECF builds intuitive 3D tools for clinicians to quickly provide
patients with high-quality and cost-effective 3D printed prosthetic
devices.

**Comment by kaitlynhova** [comment]
@andreasbastian @hobe12 what do you think of it, now?  

[production link](https://ecf-website.herokuapp.com/)

**Comment by andreasbastian** [comment]
Looks good!  Only thing I see that needs fixing is an extra period on the
first sentence on the banner text.

**Comment by hobe12** [comment]
I have some changes that i’d like to discuss. Hova, are you ready? Andreas, care to join?
S A M  H O B I S H 
samhobish.com <http://www.samhobish.com/> / 914.450.7465

**Comment by kaitlynhova** [comment]
updated on production --- Sam updated the styles to do a split hero design between logo & type 
<img width="1403" alt="screen shot 2017-02-17 at 5 38 06 pm" src="https://cloud.githubusercontent.com/assets/5474124/23089036/e2fb179a-f537-11e6-8905-3df2de57371b.png">

**Comment by andreasbastian** [comment]
Sorry, was in transit-- I really like the new layout!
