### ISSUE TITLE
Heading formatting/copy changes

### ISSUE THREAD

**Issue by andreasbastian** [e-nable/website#4]
Can we change the headings to the following (using bold here to indicate larger heading, regular type to indicate subheading):

**What We Do**
Our Mission

**Introducing LimbForge**
Deployable Prosthetic Technology

**Stay in Touch**
Join our Mailing List

**Our Supporters**
Advancing the Mission

**Get Involved**
Contact Us

**Comment by kaitlynhova** [comment]
Updated & [on production](https://ecf-website.herokuapp.com/)
