### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#5]
- [x] Increase paragraph break between titles and subtitles for each section.
- [x] Make sure these are all the same (the one for our sponsors is different)
- [x] Make sure all title and subtitle text is aligned correctly left
- [x] Menu items are too far to the right - need a margin

**Comment by kaitlynhova** [comment]
@hobe12  What do you think of the updates on [production](https://ecf-website.herokuapp.com/)?

I'm not sure how to quantify the list items exactly ^^^
