### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#6]
@andreasbastian, what do you think? Lets flesh it out here.  Here's my first stab...

Millions of people around the world living with limb-loss to not have access to prosthetic care.

ECF builds intuitive 3D tools so international clinicians can quickly provide patients with high-quality and cost-effective prosthetic devices.

**Comment by kaitlynhova** [comment]
@hobe12  Where does this live on the landing page?

**Comment by hobe12** [comment]
Need andreas approval but this would go on the hero image. hold off for now until andreas weighs in
S A M  H O B I S H 
samhobish.com <http://www.samhobish.com/> / 914.450.7465

**Comment by kaitlynhova** [comment]
Ah, ok cools I'm going to close this one and consolidate it with the original git issue.

**Comment by andreasbastian** [comment]
I think problem statement sounds good, I'd just edit down the second
statement to the following:
"ECF builds intuitive 3D tools for clinicians to quickly provide patients
with high-quality and cost-effective 3D printed prosthetic devices."
