### ISSUE TITLE
Sponsor Logos

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#7]
Please add this one in a new row centered
[BRA-0075 - CREATE OP - LOGO-01.svg.zip](https://github.com/e-nable/website/files/784396/BRA-0075.-.CREATE.OP.-.LOGO-01.svg.zip)

**Comment by kaitlynhova** [comment]
Up on [production](https://ecf-website.herokuapp.com/) now!

**Comment by hobe12** [comment]
Sorry, can we actually align it with the others on the left?


S A M  H O B I S H 
samhobish.com <http://www.samhobish.com/> / 914.450.7465
