### ISSUE TITLE
Should this go in the footer?

### ISSUE THREAD

**Issue by hobe12** [e-nable/website#8]
ECF is a tax exempt 501 (c)(3) non profit organization incorporated in Delaware, USA, in 2014.  990s and audited 2015 and 2016 financials are available upon request.

**Comment by kaitlynhova** [comment]
updates are on [production](https://ecf-website.herokuapp.com/)
<img width="1399" alt="screen shot 2017-02-17 at 5 59 25 pm" src="https://cloud.githubusercontent.com/assets/5474124/23089253/db2ab28e-f53a-11e6-9d32-d40d9a5c8e31.png">
